from PyQt5 import QtCore, QtGui, QtWidgets

import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('always')  # "error", "ignore", "always", "default", "module" or "once"

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV


# # Reading the data

df = pd.read_csv('include/winequality-red.csv', delimiter=';')

bins = [0, 5.5, 7.5, 10] # this means 3-5 are low, 6-7 are mid, 8-9 are high
labels = [0, 1, 2]
df['quality'] = pd.cut(df['quality'], bins=bins, labels=labels)
x = df[df.columns[:-1]]
y = df['quality']
sc = StandardScaler()
x = sc.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, random_state=42)



# for data in [y_train, y_test]:
#     print(data.describe())


# # K Nearest Neighbors Classifier
# print("\nK Nearest Neighbors Classifier\n")

# print("3 Neighbors\n")

# n3 = KNeighborsClassifier(n_neighbors = 3)
# n3.fit(x_train, y_train)
# pred_n3 = n3.predict(x_test)
# print("Classification Report\n")
# print(classification_report(y_test, pred_n3, labels=np.unique(pred_n3)))

# print("Confusion Matrix\n")
# print(confusion_matrix(y_test, pred_n3))





class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1908, 949)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelHeading = QtWidgets.QLabel(self.centralwidget)
        self.labelHeading.setGeometry(QtCore.QRect(0, 0, 1920, 150))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(50)
        font.setUnderline(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelHeading.setFont(font)
        self.labelHeading.setFocusPolicy(QtCore.Qt.TabFocus)
        self.labelHeading.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelHeading.setAutoFillBackground(False)
        self.labelHeading.setStyleSheet("background-color: rgb(255, 139, 139);")
        self.labelHeading.setTextFormat(QtCore.Qt.PlainText)
        self.labelHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeading.setIndent(11)
        self.labelHeading.setObjectName("labelHeading")
        self.labelHImgRight = QtWidgets.QLabel(self.centralwidget)
        self.labelHImgRight.setGeometry(QtCore.QRect(1310, 0, 200, 150))
        self.labelHImgRight.setText("")
        self.labelHImgRight.setPixmap(QtGui.QPixmap("../wine.png"))
        self.labelHImgRight.setScaledContents(True)
        self.labelHImgRight.setObjectName("labelHImgRight")
        self.labelHImgLeft = QtWidgets.QLabel(self.centralwidget)
        self.labelHImgLeft.setGeometry(QtCore.QRect(430, 0, 200, 150))
        self.labelHImgLeft.setText("")
        self.labelHImgLeft.setPixmap(QtGui.QPixmap("../wine.png"))
        self.labelHImgLeft.setScaledContents(True)
        self.labelHImgLeft.setObjectName("labelHImgLeft")
        self.labelSubHeading = QtWidgets.QLabel(self.centralwidget)
        self.labelSubHeading.setGeometry(QtCore.QRect(1010, 100, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelSubHeading.setFont(font)
        self.labelSubHeading.setObjectName("labelSubHeading")
        self.label_chng_click = QtWidgets.QLabel(self.centralwidget)
        self.label_chng_click.setGeometry(QtCore.QRect(400, 250, 1500, 100))
        self.label_chng_click.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Rage Italic")
        font.setPointSize(50)
        self.label_chng_click.setFont(font)
        self.label_chng_click.setObjectName("label_chng_click")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 330, 301, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonDA = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDA.setFont(font)
        self.pushButtonDA.setCheckable(False)
        self.pushButtonDA.setObjectName("pushButtonDA")
        self.verticalLayout.addWidget(self.pushButtonDA)
        self.pushButtonKMCA = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonKMCA.setFont(font)
        self.pushButtonKMCA.setCheckable(False)
        self.pushButtonKMCA.setObjectName("pushButtonKMCA")
        self.verticalLayout.addWidget(self.pushButtonKMCA)
        self.pushButtonDTC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDTC.setFont(font)
        self.pushButtonDTC.setCheckable(False)
        self.pushButtonDTC.setObjectName("pushButtonDTC")
        self.verticalLayout.addWidget(self.pushButtonDTC)
        self.pushButtonRFC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRFC.setFont(font)
        self.pushButtonRFC.setCheckable(False)
        self.pushButtonRFC.setObjectName("pushButtonRFC")
        self.verticalLayout.addWidget(self.pushButtonRFC)
        self.pushButtonKNNC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonKNNC.setFont(font)
        self.pushButtonKNNC.setCheckable(False)
        self.pushButtonKNNC.setObjectName("pushButtonKNNC")
        self.verticalLayout.addWidget(self.pushButtonKNNC)
        self.pushButtonSGD = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSGD.setFont(font)
        self.pushButtonSGD.setCheckable(False)
        self.pushButtonSGD.setObjectName("pushButtonSGD")
        self.verticalLayout.addWidget(self.pushButtonSGD)
        self.DA = QtWidgets.QFrame(self.centralwidget)
        self.DA.setGeometry(QtCore.QRect(400, 320, 1391, 791))
        self.DA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DA.setObjectName("DA")
        
        self.scrollArea = QtWidgets.QScrollArea(self.DA)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 1360, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1342, 2919))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        # self.alc_label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # font = QtGui.QFont()
        # font.setFamily("Bahnschrift SemiBold")
        # font.setPointSize(18)
        # self.alc_label_11.setFont(font)
        # self.alc_label_11.setAlignment(QtCore.Qt.AlignCenter)
        # self.alc_label_11.setObjectName("alc_label_11")
        # self.gridLayout_2.addWidget(self.alc_label_11, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setVerticalSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.alc_label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_2.setFont(font)
        self.alc_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_2.setObjectName("alc_label_2")
        self.gridLayout.addWidget(self.alc_label_2, 1, 1, 1, 1)
        self.alc_label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_5.setFont(font)
        self.alc_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_5.setObjectName("alc_label_5")
        self.gridLayout.addWidget(self.alc_label_5, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("imgs/chlorides.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.alc_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label.setFont(font)
        self.alc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label.setObjectName("alc_label")
        self.gridLayout.addWidget(self.alc_label, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("imgs/density.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.alc_label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_9.setFont(font)
        self.alc_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_9.setObjectName("alc_label_9")
        self.gridLayout.addWidget(self.alc_label_9, 7, 0, 1, 1)
        self.alc_label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_12.setFont(font)
        self.alc_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_12.setObjectName("alc_label_12")
        self.gridLayout.addWidget(self.alc_label_12, 12, 0, 1, 1)
        self.alc_img = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.alc_img.setText("")
        self.alc_img.setPixmap(QtGui.QPixmap("imgs/alcohol.png"))
        self.alc_img.setObjectName("alc_img")
        self.gridLayout.addWidget(self.alc_img, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("imgs/totalsulfurdioxide.png"))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("imgs/volatileacidity.png"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 11, 0, 1, 1)
        self.alc_label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_6.setFont(font)
        self.alc_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_6.setObjectName("alc_label_6")
        self.gridLayout.addWidget(self.alc_label_6, 7, 1, 1, 1)
        self.alc_label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_4.setFont(font)
        self.alc_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_4.setObjectName("alc_label_4")
        self.gridLayout.addWidget(self.alc_label_4, 3, 0, 1, 1)
        self.alc_label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_7.setFont(font)
        self.alc_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_7.setObjectName("alc_label_7")
        self.gridLayout.addWidget(self.alc_label_7, 10, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("imgs/sulphates.png"))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.alc_label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_3.setFont(font)
        self.alc_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_3.setObjectName("alc_label_3")
        self.gridLayout.addWidget(self.alc_label_3, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("imgs/residualsugar.png"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 1, 1, 1)
        self.alc_label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_8.setFont(font)
        self.alc_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_8.setObjectName("alc_label_8")
        self.gridLayout.addWidget(self.alc_label_8, 10, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("imgs/freesulfurdioxide.png"))
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("imgs/fixedacidity.png"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("imgs/citricacid.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.alc_label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        self.alc_label_10.setFont(font)
        self.alc_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.alc_label_10.setObjectName("alc_label_10")
        self.gridLayout.addWidget(self.alc_label_10, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("imgs/pH.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.frame_knn = QtWidgets.QFrame(self.centralwidget)
        self.frame_knn.setEnabled(True)
        self.frame_knn.setGeometry(QtCore.QRect(400, 320, 1390, 790))
        self.frame_knn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_knn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_knn.setObjectName("frame_knn")
        self.knn_label = QtWidgets.QLabel(self.frame_knn)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.knn_label.setFont(font)
        self.knn_label.setGeometry(QtCore.QRect(80, 60, 1300, 700))
        self.knn_label.setText("")
        # self.knn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.knn_label.setObjectName("knn_label")
        self.label_knn_cr = QtWidgets.QLabel(self.frame_knn)
        self.label_knn_cr.setGeometry(QtCore.QRect(440, 40, 290, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        self.label_knn_cr.setFont(font)
        self.label_knn_cr.setObjectName("label_knn_cr")

        #-----Randon Forest
        self.frame_rfc = QtWidgets.QFrame(self.centralwidget)
        self.frame_rfc.setEnabled(True)
        self.frame_rfc.setGeometry(QtCore.QRect(400, 320, 1390, 790))
        self.frame_rfc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rfc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rfc.setObjectName("frame_rfc")
        self.rfc_label = QtWidgets.QLabel(self.frame_rfc)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.rfc_label.setFont(font)
        self.rfc_label.setGeometry(QtCore.QRect(80, 60, 1300, 700))
        self.rfc_label.setText("")
        # self.knn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rfc_label.setObjectName("rfc_label")
        self.label_rfc_cr = QtWidgets.QLabel(self.frame_knn)
        self.label_rfc_cr.setGeometry(QtCore.QRect(440, 40, 290, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        self.label_rfc_cr.setFont(font)
        self.label_rfc_cr.setObjectName("label_rfc_cr")
        #-----

        #----- Decision Tree
        self.frame_dtc = QtWidgets.QFrame(self.centralwidget)
        self.frame_dtc.setEnabled(True)
        self.frame_dtc.setGeometry(QtCore.QRect(400, 320, 1390, 790))
        self.frame_dtc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dtc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dtc.setObjectName("frame_dtc")
        self.dtc_label = QtWidgets.QLabel(self.frame_dtc)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.dtc_label.setFont(font)
        self.dtc_label.setGeometry(QtCore.QRect(80, 60, 1300, 700))
        self.dtc_label.setText("")
        # self.knn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dtc_label.setObjectName("dtc_label")
        self.label_rfc_cr = QtWidgets.QLabel(self.frame_dtc)
        self.label_rfc_cr.setGeometry(QtCore.QRect(440, 40, 290, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        self.label_rfc_cr.setFont(font)
        self.label_rfc_cr.setObjectName("label_rfc_cr")
        #-----

        #----- Stochastic Gradient Descent
        self.frame_sgd = QtWidgets.QFrame(self.centralwidget)
        self.frame_sgd.setEnabled(True)
        self.frame_sgd.setGeometry(QtCore.QRect(400, 320, 1390, 790))
        self.frame_sgd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sgd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sgd.setObjectName("frame_sgd")
        self.sgd_label = QtWidgets.QLabel(self.frame_sgd)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.sgd_label.setFont(font)
        self.sgd_label.setGeometry(QtCore.QRect(80, 60, 1300, 700))
        self.sgd_label.setText("")
        # self.knn_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sgd_label.setObjectName("sgd_label")
        self.label_rfc_cr = QtWidgets.QLabel(self.frame_sgd)
        self.label_rfc_cr.setGeometry(QtCore.QRect(440, 40, 290, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        self.label_rfc_cr.setFont(font)
        self.label_rfc_cr.setObjectName("label_rfc_cr")
        #-----

        self.labelHeading.raise_()
        self.labelSubHeading.raise_()
        self.label_chng_click.raise_()
        self.verticalLayoutWidget.raise_()
        self.labelHImgRight.raise_()
        self.labelHImgLeft.raise_()
        self.DA.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1908, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #----------

        self.frame_kmc = QtWidgets.QFrame(self.centralwidget)
        self.frame_kmc.setEnabled(True)
        self.frame_kmc.setGeometry(QtCore.QRect(400, 320, 1390, 790))
        self.frame_kmc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kmc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kmc.setObjectName("frame_kmc")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_kmc)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cr = QtWidgets.QLabel(self.frame_kmc)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.label_cr.setFont(font)
        # self.knn_label.setGeometry(QtCore.QRect(80, 60, 1300, 700))
        self.knn_label.setText("")
        self.label_cr.setText("")
        self.label_cr.setObjectName("label_cr")
        self.horizontalLayout.addWidget(self.label_cr)
        self.label_graph_plot = QtWidgets.QLabel(self.frame_kmc)
        self.label_graph_plot.setText("")
        self.label_graph_plot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_graph_plot.setObjectName("label_graph_plot")
        self.horizontalLayout.addWidget(self.label_graph_plot)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #operations
        self.DA.hide()
        self.frame_knn.hide()
        self.frame_kmc.hide()
        self.frame_rfc.hide()
        self.frame_dtc.hide()
        self.frame_sgd.hide()
        self.pushButtonSGD.clicked.connect(self.show_sgd)
        self.pushButtonDTC.clicked.connect(self.show_dtc)
        self.pushButtonDA.clicked.connect(self.show_DA)
        self.pushButtonKNNC.clicked.connect(self.show_knn)
        self.pushButtonRFC.clicked.connect(self.show_rfc)
        self.pushButtonKMCA.clicked.connect(self.show_kmc)


    
    def show_DA(self):
        self.frame_knn.hide()
        self.frame_kmc.hide()
        self.frame_rfc.hide()
        self.frame_dtc.hide()
        self.frame_sgd.hide()
        self.label_chng_click.setText("Wine Dataset Visual Analysis")
        self.DA.show()

    def show_knn(self):
        self.DA.hide()
        self.frame_kmc.hide()
        self.frame_rfc.hide()
        self.frame_dtc.hide()
        self.frame_sgd.hide()
        self.label_chng_click.setText("K Nearest Neighbors Classifiers - 5 Neighbors")
        self.frame_knn.show()
        n5 = KNeighborsClassifier(n_neighbors = 5)
        n5.fit(x_train, y_train)
        pred_n5 = n5.predict(x_test)
        self.knn_label.setText("")
        self.knn_label.setText(classification_report(y_test, pred_n5, labels=np.unique(pred_n5)))

    def show_kmc(self):
        self.DA.hide()
        self.frame_knn.hide()
        self.frame_rfc.hide()
        self.frame_dtc.hide()
        self.frame_sgd.hide()
        self.label_chng_click.setText("K-Means Clustering Algorithm")
        self.frame_kmc.show()
        kmeans = KMeans(n_clusters=4)
        km = kmeans.fit(np.reshape(x,(len(x),11)))
        centroids = kmeans.cluster_centers_
        labels = kmeans.labels_
        pred_km = km.predict(x_test)
        self.label_cr.setText(classification_report(y_test, pred_km, labels=np.unique(pred_km), zero_division=1))
        colors = ["g.","r.","y.","b."]

        for i in range(len(x)):
            plt.plot(x[i], colors[labels[i]], markersize = 10)
            centroid_x = centroids[:,0]
            centroid_y = centroids[:,1]
            
        plt.scatter(centroid_x,centroid_y, marker = "x", s = 150, linewidths = 5, zorder = 10)
        # plt.show()
        plt.savefig('kmc_plot.jpg')
        self.label_graph_plot.setPixmap(QtGui.QPixmap("kmc_plot.jpg"))

    def show_rfc(self):
        self.DA.hide()
        self.frame_kmc.hide()
        self.frame_knn.hide()
        self.frame_dtc.hide()
        self.frame_sgd.hide()
        self.label_chng_click.setText("Random Forest Classifier")
        self.frame_rfc.show()
        rf = RandomForestClassifier()
        rf.fit(x_train, y_train)
        pred_rf = rf.predict(x_test)
        # print("Classification Report\n")
        self.rfc_label.setText("")
        self.rfc_label.setText(classification_report(y_test, pred_rf, labels=np.unique(pred_rf), zero_division=1))

    def show_dtc(self):
        self.DA.hide()
        self.frame_kmc.hide()
        self.frame_knn.hide()
        self.frame_rfc.hide()
        self.frame_sgd.hide()
        self.label_chng_click.setText("Decision Tree Classifier")
        self.frame_dtc.show()
        dt = DecisionTreeClassifier()
        dt.fit(x_train, y_train)
        pred_dt = dt.predict(x_test)
        # print("Classification Report\n")
        self.dtc_label.setText("")
        self.dtc_label.setText(classification_report(y_test, pred_dt))

    def show_sgd(self):
        self.DA.hide()
        self.frame_kmc.hide()
        self.frame_knn.hide()
        self.frame_rfc.hide()
        self.frame_dtc.hide()
        self.label_chng_click.setText("Stochastic Gradient Descent")
        self.frame_sgd.show()
        sgd = SGDClassifier()
        sgd.fit(x_train, y_train)
        pred_sgd = sgd.predict(x_test)
        # print("Classification Report\n")
        self.sgd_label.setText("")
        self.sgd_label.setText(classification_report(y_test, pred_sgd,labels=np.unique(pred_sgd)))

        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LP-2 Project"))
        self.labelHeading.setText(_translate("MainWindow", "Wine Quality Check"))
        self.labelSubHeading.setText(_translate("MainWindow", "A Project for LP-2"))
        self.label_chng_click.setText(_translate("MainWindow", ""))
        self.pushButtonDA.setText(_translate("MainWindow", "Dataset Analysis"))
        self.pushButtonKMCA.setText(_translate("MainWindow", "K-Means Clustering Algorithm"))
        self.pushButtonDTC.setText(_translate("MainWindow", "Decision Tree Classifier"))
        self.pushButtonRFC.setText(_translate("MainWindow", "Random Forest Classifier"))
        self.pushButtonKNNC.setText(_translate("MainWindow", "K Nearest Neighbors Classifier"))
        self.pushButtonSGD.setText(_translate("MainWindow", "Stochastic Gradient Descent"))
        # self.alc_label_11.setText(_translate("MainWindow", "Alcohol Quantity"))
        self.alc_label_2.setText(_translate("MainWindow", "Chloride Quantity"))
        self.alc_label_5.setText(_translate("MainWindow", "Free of Sulfur-dioxide"))
        self.alc_label.setText(_translate("MainWindow", "Alcohol Quantity"))
        self.alc_label_9.setText(_translate("MainWindow", "pH Level"))
        self.alc_label_12.setText(_translate("MainWindow", "Quantity of Volatile acidity"))
        self.alc_label_6.setText(_translate("MainWindow", "Residual Sugar Quantity"))
        self.alc_label_4.setText(_translate("MainWindow", "Citric Acid Quantity"))
        self.alc_label_7.setText(_translate("MainWindow", "Total Quantity of Sulfur-dioxide"))
        self.alc_label_3.setText(_translate("MainWindow", "Density of Wine"))
        self.alc_label_8.setText(_translate("MainWindow", "Sulphates Quantity"))
        # self.alc_label_10.setText(_translate("MainWindow", "Alcohol Quantity"))
        self.label_knn_cr.setText(_translate("MainWindow", "Classification Report"))
        self.label_rfc_cr.setText(_translate("MainWindow", "Classification Report"))
        # self.pushButton_knn_cm.setText(_translate("MainWindow", "Confusion Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
